import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Link,
} from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 11,
    paddingTop: 48,
    paddingBottom: 48,
    paddingHorizontal: 56,
    color: '#1a1a1a',
    lineHeight: 1.5,
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 12,
  },
  practiceName: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 2,
  },
  meta: {
    fontSize: 9,
    color: '#6b7280',
  },
  sectionTitle: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#6b7280',
    marginTop: 18,
    marginBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 3,
  },
  body: {
    fontSize: 11,
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap',
  },
  activityRow: {
    marginBottom: 12,
  },
  activityName: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 11,
  },
  activityDetail: {
    fontSize: 10,
    color: '#374151',
    marginTop: 1,
  },
  videoLabel: {
    fontSize: 9,
    color: '#6b7280',
    marginTop: 2,
  },
  videoLink: {
    fontSize: 9,
    color: '#2563eb',
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 56,
    right: 56,
    fontSize: 8,
    color: '#9ca3af',
    textAlign: 'center',
  },
})

export type PdfActivity = {
  name: string
  level_label: string | null
  observations: string | null
  demo_video_url?: string | null
}

type Props = {
  practiceName: string
  patientName: string
  appointmentDate: string
  appointmentType: string
  summaryBody: string
  homeActivities: PdfActivity[]
}

export function SummaryPdf({
  practiceName,
  patientName,
  appointmentDate,
  appointmentType,
  summaryBody,
  homeActivities,
}: Props) {
  const withVideos = homeActivities.filter((a) => a.demo_video_url)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.practiceName}>{practiceName}</Text>
          <Text style={styles.meta}>
            {patientName} · {appointmentType} · {appointmentDate}
          </Text>
        </View>

        {summaryBody ? (
          <>
            <Text style={styles.sectionTitle}>Visit Summary</Text>
            <Text style={styles.body}>{summaryBody}</Text>
          </>
        ) : null}

        {withVideos.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Home Exercise Plan</Text>
            {withVideos.map((a, i) => (
              <View key={i} style={styles.activityRow}>
                <Text style={styles.activityName}>
                  {a.name}
                  {a.level_label ? ` — ${a.level_label}` : ''}
                </Text>
                {a.observations ? (
                  <Text style={styles.activityDetail}>{a.observations}</Text>
                ) : null}
                <Text style={styles.videoLabel}>Demo video:</Text>
                <Link src={a.demo_video_url!} style={styles.videoLink}>
                  {a.demo_video_url}
                </Link>
              </View>
            ))}
          </>
        )}

        <Text style={styles.footer}>
          Generated by {practiceName} · {new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}
        </Text>
      </Page>
    </Document>
  )
}
